=== bgoli/sbml-specifications/sbml-level-1/version-1/schema/sbml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:annotation>
    <xsd:documentation> 
      File name : sbml.xsd 
      Description : XML Schema for the Systems Biology Markup Language
      Organization: Caltech ERATO Kitano 
      Version : 1 
      Modified : 2000-12-21 17:32 PST 
    </xsd:documentation>
  </xsd:annotation>
  <!-- SName -->
  <xsd:simpleType name="SName">
    <xsd:annotation>
      <xsd:documentation>
         SName type used for expressing
         names of components in a model
      </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="(_|[a-z]|[A-Z])(_|[a-z]|[A-Z]|[0-9])*"/>
    </xsd:restriction>
  </xsd:simpleType>
  <!-- SBase -->
  <xsd:complexType name="SBase" abstract="true">
    <xsd:annotation>
      <xsd:documentation>
        Designed to allow a modeler or a pacckage to attach
	information to each component.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="notes" minOccurs="0">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:any namespace="http://www.w3.org/1999/xhtml"
	             processContents="skip" maxOccurs="unbounded"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="annotations" minOccurs="0">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:any processContents="skip" maxOccurs="unbounded"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
  <!-- LisOfParameter  -->
  <xsd:element name="listOfParameters">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="parameter" type="Parameter"
                     maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <!-- Model -->
  <xsd:complexType name="Model">
    <xsd:complexContent>
      <xsd:extension base="SBase">
        <xsd:sequence>
          <xsd:element name="listOfUnitDefinitions" minOccurs="0">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="unitDefinition" type="UnitDefinition" maxOccurs="unbounded"/>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="listOfCompartments">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="compartment" type="Compartment" maxOccurs="unbounded"/>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="listOfSpecies">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="specie" type="Specie" maxOccurs="unbounded"/>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
          <xsd:element ref="listOfParameters" minOccurs="0"/>
          <xsd:element name="listOfRules" minOccurs="0">
            <xsd:complexType>
              <xsd:choice maxOccurs="unbounded">
                <xsd:element name="algebraicRule" type="AlgebraicRule" minOccurs="0"/>
                <xsd:element name="compartmentVolumeRule" type="CompartmentVolumeRule" minOccurs="0"/>
                <xsd:element name="specieConcentrationRule" type="SpecieConcentrationRule" minOccurs="0"/>
                <xsd:element name="parameterRule" type="ParameterRule" minOccurs="0"/>
              </xsd:choice>
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="listOfReactions">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="reaction" type="Reaction" maxOccurs="unbounded"/>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="name" type="SName" use="optional"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <!-- UnitDefinition -->
  <xsd:complexType name="UnitDefinition">
    <xsd:complexContent>
      <xsd:extension base="SBase">
        <xsd:sequence>
          <xsd:element name="listOfUnits" minOccurs="0">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="unit" type="Unit" maxOccurs="unbounded"/>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="name" type="SName" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <!-- Compartment -->
  <xsd:complexType name="Compartment">
    <xsd:complexContent>
      <xsd:extension base="SBase">
        <xsd:attribute name="name" type="SName" use="required"/>
        <xsd:attribute name="volume" type="xsd:double" use="optional" default="1"/>
        <xsd:attribute name="units" type="SName" use="optional"/>
        <xsd:attribute name="outside" type="SName" use="optional"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <!-- Specie -->
  <xsd:complexType name="Specie">
    <xsd:complexContent>
      <xsd:extension base="SBase">
        <xsd:attribute name="name" type="SName" use="required"/>
        <xsd:attribute name="compartment" type="SName" use="required"/>
        <xsd:attribute name="initialAmount" type="xsd:double" use="required"/>
        <xsd:attribute name="units" type="SName" use="optional"/>
        <xsd:attribute name="boundaryCondition" type="xsd:boolean" use="optional" default="false"/>
        <xsd:attribute name="charge" type="xsd:integer" use="optional"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <!-- Parameter -->
  <xsd:complexType name="Parameter">
    <xsd:complexContent>
      <xsd:extension base="SBase">
        <xsd:attribute name="name" type="SName" use="required"/>
        <xsd:attribute name="value" type="xsd:double" use="required"/>
        <xsd:attribute name="units" type="SName" use="optional"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <!-- UnitKind -->
  <xsd:simpleType name="UnitKind">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="ampere"/>
      <xsd:enumeration value="becquerel"/>
      <xsd:enumeration value="candela"/>
      <xsd:enumeration value="celsius"/>
      <xsd:enumeration value="coulomb"/>
      <xsd:enumeration value="dimensionless"/>
      <xsd:enumeration value="farad"/>
      <xsd:enumeration value="gram"/>
      <xsd:enumeration value="gray"/>
      <xsd:enumeration value="henry"/>
      <xsd:enumeration value="hertz"/>
      <xsd:enumeration value="item"/>
      <xsd:enumeration value="joule"/>
      <xsd:enumeration value="katal"/>
      <xsd:enumeration value="kelvin"/>
      <xsd:enumeration value="kilogram"/>
      <xsd:enumeration value="liter"/>
      <xsd:enumeration value="litre"/>
      <xsd:enumeration value="lumen"/>
      <xsd:enumeration value="lux"/>
      <xsd:enumeration value="meter"/>
      <xsd:enumeration value="metre"/>
      <xsd:enumeration value="mole"/>
      <xsd:enumeration value="newton"/>
      <xsd:enumeration value="ohm"/>
      <xsd:enumeration value="pascal"/>
      <xsd:enumeration value="radian"/>
      <xsd:enumeration value="second"/>
      <xsd:enumeration value="siemens"/>
      <xsd:enumeration value="sievert"/>
      <xsd:enumeration value="steradian"/>
      <xsd:enumeration value="tesla"/>
      <xsd:enumeration value="volt"/>
      <xsd:enumeration value="watt"/>
      <xsd:enumeration value="weber"/>
    </xsd:restriction>
  </xsd:simpleType>
  <!-- Unit -->
  <xsd:complexType name="Unit">
    <xsd:complexContent>
      <xsd:extension base="SBase">
        <xsd:attribute name="kind" type="UnitKind" use="required"/>
        <xsd:attribute name="exponent" type="xsd:integer" use="optional" default="1"/>
        <xsd:attribute name="scale" type="xsd:integer" use="optional" default="1"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <!-- Rule -->
  <xsd:simpleType name="RuleType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="scalar"/>
      <xsd:enumeration value="rate"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="Rule" abstract="true">
    <xsd:complexContent>
      <xsd:extension base="SBase">
        <xsd:attribute name="formula" type="xsd:string" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="AlgebraicRule">
    <xsd:complexContent>
      <xsd:extension base="Rule"/>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="AssignmentRule" abstract="true">
    <xsd:complexContent>
      <xsd:extension base="Rule">
        <xsd:attribute name="type" type="RuleType" use="optional" default="scalar"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="CompartmentVolumeRule">
    <xsd:complexContent>
      <xsd:extension base="AssignmentRule">
        <xsd:attribute name="compartment" type="SName" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="SpecieConcentrationRule">
    <xsd:complexContent>
      <xsd:extension base="AssignmentRule">
        <xsd:attribute name="specie" type="SName" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="ParameterRule">
    <xsd:complexContent>
      <xsd:extension base="AssignmentRule">
        <xsd:attribute name="name" type="SName" use="required"/>
        <xsd:attribute name="units" type="SName" use="optional"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <!-- Reaction -->
  <xsd:element name="specieReference">
    <xsd:complexType>
      <xsd:complexContent>
        <xsd:extension base="SBase">
          <xsd:attribute name="specie" type="xsd:string" use="required"/>
          <xsd:attribute name="stoichiometry" type="xsd:integer" use="optional" default="1"/>
          <xsd:attribute name="denominator" type="xsd:integer" use="optional" default="1"/>
        </xsd:extension>
      </xsd:complexContent>
    </xsd:complexType>
  </xsd:element>
  <xsd:complexType name="Reaction">
    <xsd:complexContent>
      <xsd:extension base="SBase">
        <xsd:sequence>
          <xsd:element name="listOfReactants">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element ref="specieReference" maxOccurs="unbounded"/>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="listOfProducts">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element ref="specieReference" maxOccurs="unbounded"/>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="kineticLaw" type="KineticLaw" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="SName" use="required"/>
        <xsd:attribute name="reversible" type="xsd:boolean" use="optional" default="true"/>
        <xsd:attribute name="fast" type="xsd:boolean" use="optional" default="false"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="KineticLaw">
    <xsd:complexContent>
      <xsd:extension base="SBase">
        <xsd:sequence>
          <xsd:element ref="listOfParameters" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="formula" type="xsd:string" use="required"/>
        <xsd:attribute name="timeUnits" type="SName" use="optional"/>
        <xsd:attribute name="substanceUnits" type="SName" use="optional"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <!-- Top-level elements allowed in an SBML document. -->
  <xsd:complexType name="sbmlDocument">
    <xsd:sequence>
      <xsd:element name="model" type="Model"/>
    </xsd:sequence>
    <xsd:attribute name="level" type="xsd:positiveInteger" use="required"/>
    <xsd:attribute name="version" type="xsd:positiveInteger" use="required"/>
  </xsd:complexType>
  <xsd:element name="sbml" type="sbmlDocument"/>
  <!-- The end. -->
</xsd:schema>

=== bgoli/sbml-specifications/sbml-level-1/version-2/draft-20030319/minimal.xml
<?xml version="1.0" encoding="UTF-8"?>
<sbml xmlns:xsi="http://www.w3.org/1999/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\afinney\My Documents\exchange-format\sbml.xsd" version="1">
	<model>
		<listOfCompartments>
			<compartment name="x"/>
		</listOfCompartments>
		<listOfSpecies>
			<specie name="y" compartment="x" initialAmount="1"/>
		</listOfSpecies>
		<listOfReactions>
			<reaction name="x">
				<listOfReactants>
					<specieReference specie="y"/>
				</listOfReactants>
				<listOfProducts>
					<specieReference specie="y"/>
				</listOfProducts>
			</reaction>
		</listOfReactions>
	</model>
</sbml>

=== bgoli/sbml-specifications/sbml-level-1/version-2/draft-20021206/units.xml
<?xml version="1.0" encoding="UTF-8"?>
<sbml xmlns:xsi="http://www.w3.org/1999/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\afinney\My Documents\exchange-format\sbml.xsd" version="1">
	<model substanceScale="-3">
		<listOfCompartments>
			<compartment name="cell"/>
		</listOfCompartments>
		<listOfSpecies>
			<specie name="x0" compartment="cell" initialAmount="1"/>
			<specie name="x1" compartment="cell" initialAmount="1"/>
			<specie name="s1" compartment="cell" initialAmount="1"/>
			<specie name="s2" compartment="cell" initialAmount="1"/>
		</listOfSpecies>
		<listOfParameters>
			<parameter name="vm" value="2" scale="-3">
				<listOfUnits>
					<unit type="mole"/>
					<unit type="litre" power="-1"/>
					<unit type="second" power="-1"/>
				</listOfUnits>
			</parameter>
			<parameter name="km" value="2" scale="-3">
				<listOfUnits>
					<unit type="mole"/>
				</listOfUnits>
			</parameter>
		</listOfParameters>
		<listOfReactions>
			<reaction name="v1">
				<listOfReactants>
					<specieReference specie="x0"/>
				</listOfReactants>
				<listOfProducts>
					<specieReference specie="s1"/>
				</listOfProducts>
				<kineticLaw formula="(vm*s1)/(km+s1)"/>
			</reaction>
			<reaction name="v2">
				<listOfReactants>
					<specieReference  specie="s1"/>
				</listOfReactants>
				<listOfProducts>
					<specieReference  specie="s2"/>
				</listOfProducts>
				<kineticLaw formula="(vm*s2)/(km+s2)"/>
			</reaction>
			<reaction name="v3">
				<listOfReactants>
					<specieReference specie="s2"/>
				</listOfReactants>
				<listOfProducts>
					<specieReference specie="x1"/>
				</listOfProducts>
				<kineticLaw formula="(vm*s1)/(km+s1)"/>
			</reaction>
		</listOfReactions>
	</model>
</sbml>

=== bgoli/sbml-specifications/sbml-level-1/version-1/final/egrules.xml
<?xml version="1.0" encoding="UTF-8"?>
<sbml xmlns:xsi="http://www.w3.org/1999/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\afinney\My Documents\exchange-format\sbml.xsd" version="1">
	<model>
		<listOfCompartments>
			<compartment name="cell" volume="1"/>
		</listOfCompartments>
		<listOfSpecies>
			<specie name="s1" compartment="cell" initialAmount="4"/>
			<specie name="s2" compartment="cell" initialAmount="2"/>
			<specie name="x0" compartment="cell" initialAmount="1"/>
			<specie name="x1" compartment="cell" initialAmount="0"/>
		</listOfSpecies>
		<listOfParameters>
			<parameter name="k1" value="1.2"/>
			<parameter name="k2" value="1000"/>
			<parameter name="k3" value="3000"/>
			<parameter name="k4" value="4.5"/>
		</listOfParameters>
		<listOfRules>
			<rule lhs="t" rhs="s1 + s2"/>
			<rule lhs="k" rhs="k3/k2"/>
			<rule lhs="s2" rhs="k*t/(1+k)"/>
			<rule lhs="s1" rhs="t-s2"/>
		</listOfRules>
		<listOfReactions>
			<reaction name="j1">
				<listOfReactants>
					<specieReference specie="x0"/>
				</listOfReactants>
				<listOfProducts>
					<specieReference specie="s1"/>
				</listOfProducts>
				<kineticLaw formula="k1*x0"/>
			</reaction>
			<reaction name="j3">
				<listOfReactants>
					<specieReference specie="s2"/>
				</listOfReactants>
				<listOfProducts>
					<specieReference specie="x1"/>
				</listOfProducts>
				<kineticLaw formula="k4*s2"/>
			</reaction>
		</listOfReactions>
	</model>
</sbml>
